---
title: "DDS_Case_Study_2"
author: "Dawson"
date: "7/26/2020"
output: html_document
---

```{r load-packages, include=FALSE}
library(e1071)
library(naivebayes)
library(data.table)
library(DT)
library(forcats)
library(ggplot2)
library(haven)
library(Hmisc)
library(plotly)
library(scales)
library(shiny)
library(stringi)
library(dplyr)
library(rsconnect)
library(ggplot2)
library(caret)
library(class)
library(GGally)
library(e1071)
library(tidyr)
library(ggpubr)
library(readr)  # for read_csv
library(knitr)  # for kable
library(RCurl)
library(skimr)
library(DataExplorer)
library(usmap)
library(maps)
library(statebins)
library(tidyverse)
library(leaps)
library(neuralnet)
library(corrplot)
library(neuralnet)
library(nnet)
library(randomForest)
library(caTools)
library(xgboost)
```

```{r include=FALSE}
#Importing the data
CaseStudyDataUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/CaseStudy2-data.csv"
CaseStudyData <-read_csv(url(CaseStudyDataUrl))
NoSalaryUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/CaseStudy2CompSet%20No%20Salary.csv"
NoSalary <-read_csv(url(NoSalaryUrl))
NoAttritionUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/CaseStudy2CompSet%20No%20Attrition.csv"
NoAttrition <-read_csv(url(NoAttritionUrl))
RegPredictUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/Case2PredictionsRegressEXAMPLE.csv"
RegPredict <-read_csv(url(RegPredictUrl))
ClassPredictUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/Case2PredictionsClassifyEXAMPLE.csv"
ClassPredict <-read_csv(url(ClassPredictUrl))
#Merging data together
CaseStudyNoSalary = merge(CaseStudyData, NoSalary, all=TRUE)
CaseStudyNoSalaryNoAttrition = merge(CaseStudyNoSalary, NoAttrition, all=TRUE)
#Modify the variables for Analysis
CaseStudy = CaseStudyNoSalaryNoAttrition %>%  mutate(
  JobInvolvement = as.factor(JobInvolvement), 
  JobSatisfaction = as.factor(JobSatisfaction), 
  PerformanceRating = as.factor(PerformanceRating), 
  RelationshipSatisfaction = as.factor(RelationshipSatisfaction), 
  WorkLifeBalance = as.factor(WorkLifeBalance),
  MaritalStatus = as.factor(MaritalStatus),
  Department = as.factor(Department),
  Gender = as.factor(Gender),
  MaritalStatus = as.factor(MaritalStatus),
  BusinessTravel = as.factor(BusinessTravel),
  JobRole = as.factor(JobRole),
  Over18 = as.factor(Over18),
  OverTime = as.factor(OverTime),
  Department= as.factor(Department), 
  StockOptionLevel = as.factor(StockOptionLevel),
  LogMonthlyIncome = log(MonthlyIncome),
  LogDistanceFromHome = log(DistanceFromHome),
  LogJobLevel = log(JobLevel),
  LogPercentSalaryHike = log(PercentSalaryHike),
  NewRelationshipSatisfaction = 
    case_when(
        RelationshipSatisfaction == 1 ~ 0,
        TRUE ~ 1,
            )
  )
CaseStudy_Omit = na.omit(CaseStudy)
```
a. Deal with the Data: EDA (Job Specific)
```{r echo=FALSE}
##Quick look at the data
skim(CaseStudy)
##Visualize Raw Provided data and Variables
data_list <- list(NoSalary = NoSalary, NoAttrition = NoAttrition)
plot_str(data_list, type = "radial", max_level = 2)
##Plot missing data from Combined 
plot_missing(CaseStudy, missing_only = TRUE, list("Good" = 0.05, "OK" = 0.4, "Bad" = 0.8, "Remove" = 1))
CaseStudyIntro = t(introduce(CaseStudy))
CaseStudyIntro
## Plot basic description for CaseStudy data
plot_intro(CaseStudy)
#Plot discrete features by arr_delay
help(plot_bar)
plot_bar(CaseStudy)
##Job Role Specific EDA
CaseStudyJobRole = CaseStudy %>% mutate(
PerformanceRating = as.numeric(as.factor(PerformanceRating)), 
JobRoleNum = as.integer(as.factor(JobRole)),
JobLevel = as.numeric(as.factor(JobLevel)),
MaritalStatusNum =
    as.numeric(as.factor(case_when(
        MaritalStatus == 'Married' ~ 0,
        TRUE ~ 1,
            ))),
EnvironmentSatisfaction = as.numeric(as.factor(EnvironmentSatisfaction)),
JobSatisfaction = as.numeric(as.factor(JobSatisfaction)),
RelationshipSatisfaction = as.numeric(as.factor(RelationshipSatisfaction)),
JobInvolvement = as.numeric(as.factor(JobInvolvement)),
WorkLifeBalance = as.numeric(as.factor(WorkLifeBalance)),
NumCompaniesWorked = as.numeric(as.factor(NumCompaniesWorked)),
AttritionNum = as.numeric(as.factor(Attrition)),
GenderNum = 
    as.numeric(as.factor(case_when(
        Gender == 'Female' ~ 0,
        TRUE ~ 1,
            ))),
Gender = as.factor(Gender),
Department = as.factor(Department),
MaritalStatus = as.factor(MaritalStatus)
                                        )
#Analyze data by JobRole
create_report(CaseStudyJobRole, y = "JobRole")
plot_correlation(CaseStudyJobRole, type = "c")
plot_correlation(CaseStudyJobRole, type = "d")
CaseStudyJobRoleNum <- CaseStudyJobRole %>% select_if(is.numeric)
plot_qq(CaseStudyJobRoleNum, by = "JobRoleNum")
cor(CaseStudyJobRoleNum, use="complete.obs", method="pearson")
#Factors by Job Role/Department (Median): Attrition MonthlySalary : JobLevel Education Age Gender MaritalStatus
#EnvironmentSatisfaction JobSatisfaction JobInvolvement Performance Rating RelationshipSatisfaction PercentSalaryHike NumCompaniesWorked WorkLifeBalance NewRelationshipStatus --> DistanceFromHome)
CaseStudyJobRoleSummary = CaseStudyJobRole %>% select(Department, JobRole, Attrition, Gender, MonthlyRate, MaritalStatus, JobLevel, Education, Age, EnvironmentSatisfaction, JobSatisfaction, JobInvolvement, PerformanceRating, RelationshipSatisfaction, PercentSalaryHike, NumCompaniesWorked, WorkLifeBalance, DistanceFromHome) 
create_report(CaseStudyJobRoleSummary, y = "JobRole")
Summary_Base_Grouped = CaseStudyJobRoleSummary %>% na.omit() %>% group_by(Department,JobRole, Attrition, JobLevel, Gender, MaritalStatus) 
Summary = summarise(Summary_Base_Grouped, MonthlyRate = mean(MonthlyRate), Employees = n(), AttritionNum = mean(as.numeric(as.factor(Attrition))), JobSatisfaction = mean(JobSatisfaction), Education = mean(Education), EnvironmentSatisfaction = mean(EnvironmentSatisfaction), JobInvolvement = mean(JobInvolvement), PerformanceRating = mean(PerformanceRating), AttritionNum = mean(AttritionNum), RelationshipSatisfaction = mean(RelationshipSatisfaction), PercentSalaryHike = mean(PercentSalaryHike), NumCompaniesWorked = mean(NumCompaniesWorked), WorkLifeBalance = mean(WorkLifeBalance), DistanceFromHome = mean(DistanceFromHome))
###Graphs
#Graph of # of Employees by Job Role
Summary %>% ggplot(aes(Employees, reorder(JobRole, Employees),fill = JobRole)) + geom_bar(stat="identity") +  labs(y = "Job Role", x = "Employees", title = "# of Employees by Job Role")
#Graph of Monthly Rate by Job Role
Summary %>% ggplot(aes(MonthlyRate, reorder(JobRole, MonthlyRate),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "Employees", title = "Monthly Rate (Mean) by Job Role")
#Graph of Monthly Rate by Department
Summary %>% ggplot(aes(Employees, reorder(Department, Employees),fill = Attrition)) + geom_col(position="fill") +  labs(y = "Department", x = "% Attrition", title = "%Attrition Rate by Department")
#Graph of Monthly Rate by Job Role
Summary %>% ggplot(aes(Employees, reorder(JobRole, Employees),fill = Attrition)) + geom_col(position="fill") +  labs(y = "Job Role", x = "% Attrition", title = "%Attrition Rate by Job Role")
#Graph of Monthly Rate by Department
Summary %>% ggplot(aes(Employees, reorder(Department, Employees),fill = Attrition)) + geom_col(position="fill") +  labs(y = "Department", x = "% Attrition", title = "%Attrition Rate by Department")
#Graph of MonthlyRate Rate by JobRole by Attrition
Summary %>% ggplot(aes(MonthlyRate, reorder(JobRole, Employees),fill = Attrition)) + geom_col(stat="identity") +  labs(y = "JobRole", x = "MonthlyRate", title = "Monthly Rate by JobRole by Attrition")
#Graph of Job Satisfaction by Job Role
Summary %>% ggplot(aes(JobSatisfaction, reorder(JobRole, JobSatisfaction),fill = Attrition)) + geom_boxplot() +  labs(y = "Job Role", x = "JobSatisfaction", title = "JobSatisfaction by Job Role")
#Graph of EnvironmentSatisfaction by Job Role
Summary %>% ggplot(aes(EnvironmentSatisfaction, reorder(JobRole, EnvironmentSatisfaction),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "EnvironmentSatisfaction", title = "EnvironmentSatisfaction by Job Role")
#Graph of EnvironmentSatisfaction by Job Role
Summary %>% ggplot(aes(JobInvolvement, reorder(JobRole, JobInvolvement),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "JobInvolvement", title = "JobInvolvement by Job Role")
#Graph of EnvironmentSatisfaction by Department
Summary %>% ggplot(aes(PerformanceRating, reorder(Department, PerformanceRating),fill = Department)) + geom_boxplot() +  labs(y = "Department", x = "PerformanceRating", title = "PerformanceRating by Department")
#Graph of EnvironmentSatisfaction by Job Role
Summary %>% ggplot(aes(PerformanceRating, reorder(JobRole, PerformanceRating),fill = Attrition)) + geom_boxplot() +  labs(y = "Job Role", x = "PerformanceRating", title = "PerformanceRating by Job Role")
#Graph of WorkLifeBalance & Attrition by JobRole
Summary %>% ggplot(aes(WorkLifeBalance, reorder(JobRole, WorkLifeBalance),fill = Attrition)) + geom_boxplot() +  labs(y = "Department", x = "WorkLifeBalance", title = "WorkLifeBalance & Attrition by JobRole")
#Graph of WorkLifeBalance by Job Role
Summary %>% ggplot(aes(WorkLifeBalance, reorder(JobRole, WorkLifeBalance),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "WorkLifeBalance", title = "WorkLifeBalance by Job Role")
#Graph of WorkLifeBalance & Attrition by JobRole
Summary %>% ggplot(aes(DistanceFromHome, reorder(JobRole, DistanceFromHome),fill = Attrition)) + geom_boxplot() +  labs(y = "Department", x = "DistanceFromHome", title = "DistanceFromHome & Attrition by JobRole")
#Graph of DistanceFromHome by Job Role
Summary %>% ggplot(aes(DistanceFromHome, reorder(JobRole, DistanceFromHome),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "DistanceFromHome", title = "DistanceFromHome by Job Role")
#Graph of PercentSalaryHike by Job Role
Summary %>% ggplot(aes(PercentSalaryHike, reorder(JobRole, PercentSalaryHike),fill = JobRole)) + geom_boxplot() +  labs(y = "Job Role", x = "PercentSalaryHike", title = "PercentSalaryHike by Job Role")
#Graph of Education by Job Role
Summary %>% ggplot(aes(Education, reorder(JobRole, Education),fill = Education)) + geom_boxplot() +  labs(y = "Job Role", x = "Education", title = "Education by Job Role")
#Graph of WorkLifeBalance & Attrition by JobRole
Summary %>% ggplot(aes(WorkLifeBalance, reorder(JobLevel, JobLevel),fill = Attrition)) + geom_boxplot() +  labs(y = "JobLevel", x = "WorkLifeBalance", title = "WorkLifeBalance & Attrition by JobLevel")
#Graph of W# of Employees by Attrition
Summary %>% filter(!is.na(Attrition)) %>% ggplot(aes(Employees,reorder(Attrition, Employees),fill = Attrition)) + geom_bar(stat='identity') +  labs(y = "Attrition", x = "# of Employees", title = "# of Employees by Attrition")
#Graph of W# of Employees by Attrition
Summary %>% filter(!is.na(Attrition)) %>% ggplot(aes(Employees,reorder(Attrition, Employees),fill = Attrition)) + geom_bar(stat='identity') +  labs(y = "Attrition", x = "# of Employees", title = "# of Employees by Attrition")
```
1. Multiple Linear Regression Model for Predicting Monthly Income
```{r echo=FALSE}
#Data excluding lines with MonthlyIncome Missing
CaseStudyIncome = CaseStudy[!is.na(CaseStudy$MonthlyIncome),]
##Modeling
models <- lm(MonthlyIncome ~ Age + JobLevel + TotalWorkingYears + Department + YearsAtCompany + NewRelationshipSatisfaction + PerformanceRating + Attrition, data = CaseStudyIncome)
summary(models)
par(mfrow = c(2, 2))  # Split the plotting panel into a 2 x 2 grid
plot(models)
summary(models)
confint(models)
RSS <- c(crossprod(models$residuals))
MSE <- RSS / length(models$residuals)
RMSE <- sqrt(MSE)
sig2 <- RSS / models$df.residual
RSS
MSE
RMSE
sig2
ggplot(data=models, aes(models$residuals)) +
geom_histogram(binwidth = 1, color = "black", fill = "purple4") +
theme(panel.background = element_rect(fill = "white"),
axis.line.x=element_line(),
axis.line.y=element_line()) +
ggtitle("Histogram for Model Residuals")
CaseStudyIncomePredict = CaseStudy[!is.na(CaseStudy$MonthlyIncome),]
PredictIncome = predict(models, newdata = CaseStudyIncomePredict, interval = 'prediction')
head(PredictIncome)

data2 = data.frame(CaseStudyIncomePredict, regression = PredictIncome)
PredictedIncome = data2 %>% mutate(MonthlyIncome = as.numeric(regression.fit)) %>% select(ID, MonthlyIncome) %>% na.omit()
skim(PredictedIncome)
write.csv(PredictedIncome,"C:/Users/Dawson/Documents/GitHub/Analytics/Kaggle/Kaggle/DDS_LM_Predictions.csv", row.names = FALSE)
```

2.  Knn/Bayes for categorizing Attrition

```{r echo=FALSE}
#Data excluding lines with Atttrition Missing
CaseStudy2 = CaseStudy %>% select(-MonthlyIncome,-LogMonthlyIncome) %>% mutate(Attrition = as.factor(Attrition))
CaseStudyAttrition = CaseStudy2[!is.na(CaseStudy2$Attrition),]
#create_report(CaseStudyAttrition, y = "Attrition")
Attrition = CaseStudyAttrition %>% mutate(WorkLifeBalance = as.integer(as.factor(WorkLifeBalance)),JobInvolvement = as.integer(as.factor(JobInvolvement)), MaritalStatus = as.integer(as.factor(MaritalStatus)), DistanceFromHome = log(as.integer(as.factor(DistanceFromHome))), TrainingTimesLastYear = as.integer(as.factor(TrainingTimesLastYear)), Department = as.integer(as.factor(Department)), OverTime = as.integer(as.factor(OverTime)), JobRole = as.integer(as.factor(JobRole)), AttritionNum = as.integer(as.factor(Attrition)), JobSatisfaction = as.integer(as.factor(JobSatisfaction)), PerformanceRating = as.integer(as.factor(PerformanceRating)), Attrition = as.factor(Attrition),  EducationField = as.integer(as.factor(EducationField)), LogAge = as.numeric(log(Age)), LogYearsWithCurrManager = log(as.integer(as.factor(YearsWithCurrManager))), EnvironmentSatisfaction = as.integer(as.factor(EnvironmentSatisfaction))) %>% select(ID, WorkLifeBalance, JobInvolvement, MaritalStatus, DistanceFromHome,OverTime, LogAge, LogYearsWithCurrManager, LogJobLevel, PerformanceRating, EducationField, NumCompaniesWorked, Attrition)
skim(Attrition)
fit.1 <- glm(Attrition == "No" ~ ., data = Attrition)
summary(fit.1)
glimpse(Attrition)
#Setting stage for Knn
set.seed(6)
splitPerc = .75
trainIndices = sample(1:dim(Attrition)[1],round(splitPerc * dim(Attrition)[1]))
train = Attrition[trainIndices,]
test = Attrition[-trainIndices,]
##utilize best k
classifications = knn(train[,c(1:9)],test[,c(1:9)],train$Attrition, prob = TRUE, k = 2)
table(classifications,test$Attrition)
confusionMatrix(table(classifications,test$Attrition))
table = table(classifications,test$Attrition)
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(table)
prop.table(table)
```

```{r echo=FALSE}
#Explore some best ideas for better k-values; Not sure if it can be improved
AttritionNum = CaseStudyAttrition %>% mutate(WorkLifeBalance = as.integer(as.factor(WorkLifeBalance)),JobInvolvement = as.integer(as.factor(JobInvolvement)), MaritalStatus = as.integer(as.factor(MaritalStatus)), DistanceFromHome = log(as.integer(as.factor(DistanceFromHome))), TrainingTimesLastYear = as.integer(as.factor(TrainingTimesLastYear)), Department = as.integer(as.factor(Department)), OverTime = as.integer(as.factor(OverTime)), JobRole = as.integer(as.factor(JobRole)), AttritionNum = as.integer(as.factor(Attrition)), JobSatisfaction = as.integer(as.factor(JobSatisfaction)),Attrition = as.factor(Attrition), LogAge = as.numeric(log(Age)), LogYearsWithCurrManager = log(as.integer(as.factor(YearsWithCurrManager))), EnvironmentSatisfaction = as.integer(as.factor(EnvironmentSatisfaction)), JobLevel = as.integer(as.factor(JobLevel)))
plot_qq(AttritionNum, by = "Attrition")
skim(AttritionNum)
cr1 <- AttritionNum %>% 
    select_if(is.numeric) %>% 
    cor(use = "pair")

cr2 <- cr1[order(cr1[, "AttritionNum"], decreasing = TRUE),
           order(cr1[, "AttritionNum"], decreasing = TRUE)]

corrplot::corrplot(cr2[1:10, 1:10], type = "upper")
corrplot::corrplot(cr2[c(1,11:20),c(1,11:20)], type = "upper")
corrplot::corrplot(cr2[c(1,21:30),c(1,21:30)], type = "upper")
corrplot::corrplot(cr2[c(1,31:34),c(1,31:34)], type = "upper")
##Try another KNn
x <- subset(Attrition, select=-Attrition)
y <- Attrition %>% select(ID,Attrition)

obj2 <- tune.knn(x, y$Attrition, k = 1:50, tunecontrol = tune.control(sampling = "boot"))
  summary(obj2)
  plot(obj2)
```
3. Moving to Alternative to Knn -> SVM

```{r echo=FALSE}
svm_model <- svm(Attrition ~ ., data=Attrition)
summary(svm_model)
svm_model1 <- svm(x,y$Attrition)
summary(svm_model1)
pred <- predict(svm_model1,x)
system.time(pred <- predict(svm_model1,x))
table(pred,y$Attrition)
cm1 = table(pred,y$Attrition)
sensitivity(cm1)
specificity(cm1)
svm_tune <- tune(svm, train.x=x, train.y=y$Attrition, 
              kernel="radial", ranges=list(cost=10^(-1:2), gamma=c(.5,1,2)))
print(svm_tune)

svm_model_after_tune <- svm(Attrition ~ ., data=Attrition, kernel="radial", cost=1, gamma=0.5)
summary(svm_model_after_tune)

#best.svm(x, tunecontrol = tune.control(), ...)

pred <- predict(svm_model_after_tune,x)
system.time(predict(svm_model_after_tune,x))

table(pred,y$Attrition)
cm2 = table(pred,y$Attrition)
sensitivity(cm2)
specificity(cm2)
head(pred)
data3 = data.frame(y, PredictedAttrition = pred)
skim(data3)
head(data3)
PredictedAttrition = data3 %>% mutate(PredictedAttrition = as.factor(PredictedAttrition)) %>% select(ID, PredictedAttrition) %>% na.omit()
skim(PredictedAttrition)
write.csv(PredictedAttrition,"C:/Users/Dawson/Documents/GitHub/Analytics/Kaggle/Kaggle/DDS_SVM_Class_Predictions.csv", row.names = FALSE)
```